### ISSUE TITLE
Language accent not displayed properly in Slack

### ISSUE THREAD

**Issue by thcottin** [stevenosloan/slack-notifier#28]
Hi @stevenosloan,

Thanks for this wrapper that's very useful. I have a problem though with french accent being rendered as question marks when they land in Slack when posted with your client.

I tried a manual curl to my Slack webhook and accents are parsed ok.
Could you help me on this?

Thanks !

**Comment by stevenosloan** [comment]
Hey @thcottin, do you mind trying it off of the master branch of github? I had a fix I merged in and got caught up w/ things at work before being able to release.

```ruby
gem "slack-notifier", git: "git@github.com:stevenosloan/slack-notifier.git",
                      branch: "master"
```

**Comment by thcottin** [comment]
Hey @stevenosloan, sorry I missed your answer. Just tried it and still get a question mark instead of a "â". Should I escape the string before?

**Comment by stevenosloan** [comment]
Hmm, interesting. Do you happen to know what encoding the string is before it's passed to slack notifier?

Scrub *should* only replace unrecognized characters, but I'm not sure how that ends up acting w/ different encodings. (everything I've done has been UTF-8 => UTF-8)

**Comment by thcottin** [comment]
I'm pretty sure it's UTF-8. Same problem if I force the UTF-8 encoding anyway. I keep trying things out, will let you know if I find a fix.

**Comment by thcottin** [comment]
I have just tried muting the "fix_encoding" method in the LinkFormatter and accented characters are displayed correctly in Slack. Any idea why it's doing this?
Thanks!

**Comment by stevenosloan** [comment]
No that's really odd -- all that's doing (from master at least) is calling `#scrub` on the string. You're trying it with the github master version right? The fix_encoding method shouldn't be present anymore.

**Comment by thcottin** [comment]
Issue solved using the master branch! I don't know why it did not work before. Thanks again for your help!

**Comment by nafu** [comment]
@stevenosloan 
Thanks this feature.
https://github.com/stevenosloan/slack-notifier/commit/a68a5eaa07f2aebac7c039d06ba310f2170dbe75#diff-dd9694ea955bfd766a80d7c92a1b4d57R56

Could you update the gem version?
I'm looking forward to it.

**Comment by mono0926** [comment]
Oh, it is a coincidence!
I cannot post Japanese message :jp: 

I'm looking forward to it :sweat_drops:

**Comment by stevenosloan** [comment]
thanks for the reports, fix is out now in `1.2.1` :tada:

**Comment by nafu** [comment]
Thanks a lot. :smile:

**Comment by mono0926** [comment]
Great :tada:
